import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    showProgressSidebar: true,
    recentlyViewedCourses: [],
    labelNames: { // All the valid labels for the current discipline
      listB: "List B",
      listC: "List C",
      level400: "400 Level",
      commonCore: "Common Core",
      eceCore: "ECE Core",
      isCustom: "Custom Course",
    },
    graduationRequirements: {  //Graduation requirements for the current discipline
      totalCredits: 162.5,
      auBaseRequirements: [
        {
          name: "Mathematics (Math)",
          aus: ["mathematics"],
          value: 220,
          type: "Units"
        },
        {
          name: "Natural Sciences (NS)",
          aus: ["naturalSciences"],
          value: 200,
          type: "Units"
        },
        {
          name: "Complementary Studies (CS)",
          aus: ["complementaryStudies"],
          value: 240,
          type: "Units"
        },
        {
          name: "Engineering Sciences (ES)",
          aus: ["engineeringSciences"],
          value: 400,
          type: "Units"
        },
        {
          name: "Engineering Design (ED)",
          aus: ["engineeringDesign"],
          value: 400,
          type: "Units"
        },
      ],
      auCombinedRequirements: [
        {
          name: "ES+ED",
          aus: ["engineeringSciences", "engineeringDesign"],
          value: 1000,
          type: "Units"
        },
        {
          name: "Math+NS",
          aus: ["mathematics", "naturalSciences"],
          value: 420,
          type: "Units"
        },
        {
          name: "Total AUs",
          aus: ["mathematics", "naturalSciences", "complementaryStudies", "engineeringSciences", "engineeringDesign"],
          value: 1950,
          type: "Units"
        },
      ],
      additionalRequirements: [
        {
          name: "400 Level",
          labels: ["level400"],
          value: 5,
          type: "Courses"
        },
        {
          name: "Common Core",
          labels: ["commonCore"],
          value: 10,
          type: "Courses"
        },
        {
          name: "ECE Core",
          labels: ["eceCore"],
          value: 22,
          type: "Courses"
        },
        {
          name: "List B/C",
          labels: ["listB", "listC"],
          value: 4,
          type: "Courses"
        },
        {
          name: "Complementary Electives",
          labels: ["complementaryCredits"],
          value: 9,
          type: "Credits"
        }
      ]
    },
    courses: [
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "100",
        "courseCode": "APSC 100",
        "id": "APSC 100 Engineering Practice l 2015-2016",
        "name": "Engineering Practice l",
        "semester": "Summer",
        "hasLecture": 0,
        "hasLab": 0,
        "hasTutorial": 0,
        "description": "This course introduces fundamental professional engineering skills and provides an opportunity to apply engineering science and mathematics content in situations emulating professional practice. It consists of three modules: Module 1. Problem analysis and modeling; Module 2. Experimentation and measurement; Module 3: Engineering design. The course provides an introduction to personal learning styles, team dynamics, oral and written presentation skills, laboratory data collection, analysis and presentation, project management, information management, problem analysis and modeling, numeric computation, economics, design methodologies, and workplace safety. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 6,
          "naturalSciences": 16,
          "complementaryStudies": 40,
          "engineeringSciences": 40,
          "engineeringDesign": 30,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "completed",
        "credits": "4",
        "schedule": [["2029-01-01 08:30", "2029-01-01 09:30"], ["2029-01-03 09:30", "2029-01-03 10:30"]],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "101",
        "courseCode": "APSC 101",
        "id": "APSC 101 Engineering Problem Solving and Modeling 2015-2016",
        "name": "Engineering Problem Solving and Modeling",
        "semester": "Fall",
        "hasLecture": 0,
        "hasLab": 0,
        "hasTutorial": 0,
        "description": "This course provides an opportunity for students to develop complex problem solving and critical thinking skills and to apply engineering science knowledge in modeling physical systems through computational software. Examples and project topics are chosen to complement instruction in engineering science and mathematics courses. Ethical, economic, and social factors are considered in engineering problem solving. ",
        "professor": "Dr. Tony Noble",
        "notes": "NOTE: This course covers the content and objectives of APSC 100 Module 1, and is available by permission only. (6/0/12/18/12) ",
        "accreditationUnits": {
          "mathematics": 6,
          "naturalSciences": 0,
          "complementaryStudies": 12,
          "engineeringSciences": 18,
          "engineeringDesign": 12,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "Permission of the instructor or Associate Dean (Academic) ",
        "corequisites": "",
        "exclusions": "APSC 100  ",
        "isCurrentlyOffered": 1,
        "status": "inProgress",
        "credits": "2",
        "schedule": [["2029-01-01 14:30", "2029-01-01 17:30"]],

      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "102",
        "courseCode": "APSC 102",
        "id": "APSC 102 Experimentation and Design 2015-2016",
        "name": "Experimentation and Design",
        "semester": "Fall/Winter",
        "hasLecture": 0,
        "hasLab": 0,
        "hasTutorial": 0,
        "description": "This course introduces concepts of planning and designing experiments determine or measure particular system characteristics. The course content includes error analysis, data analysis and representation in Excel, and the design of experimental investigation for simple systems. ",
        "professor": "Dr. Tony Noble",
        "notes": "NOTE: This course covers the content and objectives of APSC 100 Module 2, and is available by permission only. ",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 16,
          "complementaryStudies": 4,
          "engineeringSciences": 16,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "Permission of the instructor or Associate Dean (Academic) ",
        "corequisites": "",
        "exclusions": "APSC 100  ",
        "isCurrentlyOffered": 1,
        "status": "inProgress",
        "credits": "3",
        "schedule": [["2029-01-01 18:00", "2029-01-01 21:00"], ["2029-01-03 18:00", "2029-01-03 21:00"]],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "103",
        "courseCode": "APSC 103",
        "id": "APSC 103 Engineering Design Project 2015-2016",
        "name": "Engineering Design Project",
        "semester": "Winter",
        "hasLecture": 0,
        "hasLab": 0,
        "hasTutorial": 0,
        "description": "This is a client-based team design project which develops skills including design, project management, technical communications, and professionalism. Students work in teams to define problems, gather and identify appropriate information, work effectively with teammates, generate ideas, select ideas, and implement a solution to a presented problems from a client. ",
        "professor": "Dr. Tony Noble",
        "notes": "NOTE: This course covers the content and objectives of APSC 100 Module 3, and is available by permission only. (0/0/24/6/18) ",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 0,
          "complementaryStudies": 24,
          "engineeringSciences": 6,
          "engineeringDesign": 18,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "Permission of the instructor or Associate Dean (Academic) ",
        "corequisites": "",
        "exclusions": "APSC 100  ",
        "isCurrentlyOffered": 1,
        "status": "saved",
        "credits": "3",
        "schedule": [["2029-01-02 08:30", "2029-01-02 09:30"], ["2029-01-04 09:30", "2029-01-04 10:30"]],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "111",
        "courseCode": "APSC 111",
        "id": "APSC 111 Mechanics 2015-2016",
        "name": "Mechanics",
        "semester": "Fall",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "This course is an introduction to Newtonian mechanics in the context of engineering applications. Lecture topics are: vectors, motion of a particle, particle dynamics, work and energy, statics and dynamics of rigid bodies, conservation of energy, momentum, and collisions. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 42,
          "complementaryStudies": 0,
          "engineeringSciences": 0,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 1,
          "listB": 1,
          "listC": 1,
          "complementaryCredits": 1,
          "isCustom": 1,
        },
        "prerequisites": "",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "saved",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "112",
        "courseCode": "APSC 112",
        "id": "APSC 112 Electricity and Magnetism 2015-2016",
        "name": "Electricity and Magnetism",
        "semester": "Winter",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "This course continues from APSC 111 to introduce electricity and further develop fundamental ideas of mechanics in the context of engineering applications. Lecture topics include: oscillations and waves, electric charge, electrical current and resistance, EMF, D.C. circuits and electrical measurements, electric field and potential, magnetic fields and their origin, and electromagnetic induction. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 31,
          "complementaryStudies": 0,
          "engineeringSciences": 11,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 111 and APSC 171 ",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "completed",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "131",
        "courseCode": "APSC 131",
        "id": "APSC 131 Chemistry and Materials 2015-2016",
        "name": "Chemistry and Materials",
        "semester": "Fall",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "This course provides an introduction to the chemistry of materials: thermochemistry, heat, work, internal energy, enthalpy and the first law of thermodynamics; gas laws in ideal and non-ideal systems; phase equilibria in one component systems; concepts of bonding in the classification of materials; the physical, electrical and mechanical properties of metals, polymers, semiconductors and ceramics; techniques of characterizing materials. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 31,
          "complementaryStudies": 0,
          "engineeringSciences": 11,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "132",
        "courseCode": "APSC 132",
        "id": "APSC 132 Chemistry and its Applications 2015-2016",
        "name": "Chemistry and its Applications",
        "semester": "Summer",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "This course combines fundamentals of chemistry with the engineering issues associated with them. Areas of study are entropy and the second law of thermodynamics, thermodynamics, chemical equilibrium, electrochemistry, chemical kinetics and organic chemistry. Environmental issues associated with each of these topics will be incorporated into lectures when appropriate. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 31,
          "complementaryStudies": 0,
          "engineeringSciences": 11,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 131 ",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "saved",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "142",
        "courseCode": "APSC 142",
        "id": "APSC 142 Introduction to Computer Programming for Engineers 2015-2016",
        "name": "Introduction to Computer Programming for Engineers",
        "semester": "Fall/Winter",
        "hasLecture": 1,
        "hasLab": 1,
        "hasTutorial": 0,
        "description": "This course introduces concepts, theory and practice of computer programming. Implementation uses microcomputers. The emphasis is on the design of correct and efficient algorithms and on programming style. Applications are made to engineering problems. ",
        "professor": "Dr. Tony Noble",
        "notes": "NOTE: The fall term delivery of this course is intended for students in the ECE direct-entry program, and enrolment in this term will require permission of the Associate Dean (Academic). ",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 24,
          "engineeringDesign": 12,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "151",
        "courseCode": "APSC 151",
        "id": "APSC 151 Earth Systems and Engineering 2015-2016",
        "name": "Earth Systems and Engineering",
        "semester": "Fall",
        "hasLecture": 1,
        "hasLab": 1,
        "hasTutorial": 0,
        "description": "This course provides an introduction to the complex Earth System (which encompasses the solid earth, hydrosphere, atmosphere, and biosphere), and our interactions with it. Using the Earth System as a framework, and coupled with the over-arching theme of sustainability, key concepts/issues relevant to engineers are dealt with, including: population demographics and resource usage; geopolitics; modeling of \"fuzzy\" systems; risk assessment and risk management; local- and global-scale impacts of engineering works on the government; short- and long-term natural and anthropogenic changes (including global warming); moral and ethical considerations. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 24,
          "complementaryStudies": 12,
          "engineeringSciences": 12,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "161",
        "courseCode": "APSC 161",
        "id": "APSC 161 Engineering Graphics 2015-2016",
        "name": "Engineering Graphics",
        "semester": "Fall",
        "hasLecture": 1,
        "hasLab": 1,
        "hasTutorial": 0,
        "description": "The principal objectives of the course are (1) to develop the student's ability to visualize and communicate three-dimensional shapes and (2) to acquire the skills needed to use computer-aided design software. Topics covered are orthographic projection, isometric sketching, auxiliary and section views as well as dimensioning and working drawings. Computer-aided design software is used to create solid models of the parts and assemblies as well as to generate dimensioned drawings. Students apply their learning in a project where they design their own version of a consumer product. Students learn by hands-on exercises in free-hand sketching and computer-based drawing. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 37,
          "engineeringDesign": 5,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "completed",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "171",
        "courseCode": "APSC 171",
        "id": "APSC 171 Calculus I 2015-2016",
        "name": "Calculus I",
        "semester": "Fall",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "Functions, limits, derivatives; optimization, rate problems, exponentials, logarithms, inverse trigonometric functions; exponential growth as an example of a differential equation. Fundamental Theorem of Calculus, Riemann integral; applications to problems involving areas, volumes, mass, charge, work, etc. Some integration techniques. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 42,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 0,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "completed",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "172",
        "courseCode": "APSC 172",
        "id": "APSC 172 Calculus II 2015-2016",
        "name": "Calculus II",
        "semester": "Winter",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "This course continues calculus concepts from APSC 171, including space curves, speed, and velocity. Functions of several variables, partial derivatives, differentials, error estimates, gradient, maxima and minima. Double and triple integrals, polar and cylindrical coordinates; applications to mass, center of mass, moment. Series, power series; Taylor polynomial approximations, error analysis. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 42,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 0,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 171  ",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "completed",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "174",
        "courseCode": "APSC 174",
        "id": "APSC 174 Introduction to Linear Algebra 2015-2016",
        "name": "Introduction to Linear Algebra",
        "semester": "Winter",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "Systems of linear equations; real vectors spaces and subspaces; linear combinations and linear spans; linear dependence and linear independence; applications to systems of linear equations and their solution via Gaussian elimination; bases and dimension of real vector spaces; linear transformations, range, kernel and Rank-Nullity theorem; matrix representation of a linear transformation; composition of linear transformations and matrix multiplication; invertible matrices and determinants; eigenvalues and eigenvectors of square matrices. Applications of the course material to engineering systems are illustrated. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 42,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 0,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "completed",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "191",
        "courseCode": "APSC 191",
        "id": "APSC 191 Professional Engineering Skills 2015-2016",
        "name": "Professional Engineering Skills",
        "semester": "Fall/Winter",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "This course is identical in content to APSC 190. The material normally delivered in APSC 190 in the first week of the winter term will be covered in evening sessions in the fall term in APSC 191. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 0,
          "complementaryStudies": 42,
          "engineeringSciences": 0,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "completed",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "200",
        "courseCode": "APSC 200",
        "id": "APSC 200 Engineering Design and Practice II (SAMPLE) 2015-2016",
        "name": "Engineering Design and Practice II (SAMPLE)",
        "semester": "Fall/Winter",
        "hasLecture": 0,
        "hasLab": 0,
        "hasTutorial": 0,
        "description": "In this course students will participate constructively on teams to create solutions to open-ended complex problems, using standard design methods and tools. This project-based course provides instruction primarily in the first 6 weeks of the semester focusing on problem scoping, creativity and idea generation, decision making incorporating technical, economic, societal, and environmental factors, safety, engineering codes and regulations, and engineering ethics. The final 6 weeks of the course centre around a design project delivered by each discipline. This course is integrated with APSC-293, and coordinated by the same instructor. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 0,
          "complementaryStudies": 12,
          "engineeringSciences": 0,
          "engineeringDesign": 36,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 100 ",
        "corequisites": "APSC 293 ",
        "exclusions": "MECH 212 ",
        "isCurrentlyOffered": 1,
        "status": "completed",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "APSC",
        "code": "293",
        "courseCode": "APSC 293",
        "id": "APSC 293 Engineering Communications l (SAMPLE) 2015-2016",
        "name": "Engineering Communications l (SAMPLE)",
        "semester": "Fall/Winter",
        "hasLecture": 0,
        "hasLab": 0,
        "hasTutorial": 0,
        "description": "This course provides an introduction to effective engineering writing and speaking skills with the emphasis on professional correspondence, engineering reports, oral briefings, and formal oral presentations. These skills are developed in lectures and small group tutorials. This course is integrated with APSC 200, and coordinated by the same instructor. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 0,
          "complementaryStudies": 12,
          "engineeringSciences": 0,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 100 ",
        "corequisites": "APSC 200 or permission of instructor ",
        "exclusions": "APSC 292, CHEE 260, ELEC 291, ELEC 391, GEOL 291, GEOL 292, MECH 290 ",
        "isCurrentlyOffered": 1,
        "status": "completed",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "CHEE",
        "code": "209",
        "courseCode": "CHEE 209",
        "id": "CHEE 209 Analysis of Process Data (SAMPLE) 2015-2016",
        "name": "Analysis of Process Data (SAMPLE)",
        "semester": "Fall",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "Statistical methods for analyzing and interpreting process data are discussed, with special emphasis on techniques for continuous improvement of process operations. Topics include: role of data in assessing process operation, identifying major problems, graphical and numerical summaries, principles of valid inference, probability distributions for discrete and continuous data, process capability, comparing process performance to target values, comparing performances of two processes, control charts, and an introduction to linear regression analysis. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 27,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 15,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 171, APSC 172, APSC 174  ",
        "corequisites": "",
        "exclusions": "STAT 263, STAT 268, STAT 269, MTHE 367 (STAT 367) ",
        "isCurrentlyOffered": 1,
        "status": "completed",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "CHEE",
        "code": "210",
        "courseCode": "CHEE 210",
        "id": "CHEE 210 Thermodynamic Properties of Fluids (SAMPLE) 2015-2016",
        "name": "Thermodynamic Properties of Fluids (SAMPLE)",
        "semester": "Winter",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "This course is an introduction to the thermodynamics of fluids for chemical engineering applications. Concepts to be learned include heat, work, internal energy, enthalpy, entropy, and state functions. Students will understand how to calculate heat and work effects arising from physical processes such as expansion and contraction of fluids and how to calculate the thermodynamic properties of fluids using equations of state, residual properties and correlations. Course concepts will be reinforced in a project. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 42,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "CHEE 221 (or MINE 201) ",
        "corequisites": "None ",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "CHEE",
        "code": "218",
        "courseCode": "CHEE 218",
        "id": "CHEE 218 Laboratory Projects I (SAMPLE) 2015-2016",
        "name": "Laboratory Projects I (SAMPLE)",
        "semester": "Fall",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "Introduction to the fundamentals and principles of chemical engineering, with applications to chemical and biochemical processes, via an analysis of processing units including distillation, crystallization and combustion. Specific topics include conservation equations for mass and energy, process flow diagrams, material and energy balances, chemical reaction fundamentals, and applications of the First Law of Thermodynamics. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 30,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 131, APSC 132, APSC 172, or permission of the department ",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "CHEE",
        "code": "221",
        "courseCode": "CHEE 221",
        "id": "CHEE 221 Chemical Processes and Systems (SAMPLE) 2015-2016",
        "name": "Chemical Processes and Systems (SAMPLE)",
        "semester": "Fall",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "Introduction to the fundamentals and principles of chemical engineering, with applications to chemical and biochemical processes, via an analysis of processing units including distillation, crystallization and combustion. Specific topics include conservation equations for mass and energy, process flow diagrams, material and energy balances, chemical reaction fundamentals, and applications of the First Law of Thermodynamics. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 42,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 131, APSC 132, APSC 172, or permission of the department ",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "CHEE",
        "code": "222",
        "courseCode": "CHEE 222",
        "id": "CHEE 222 Process Dynamics and Numerical Methods (SAMPLE) 2015-2016",
        "name": "Process Dynamics and Numerical Methods (SAMPLE)",
        "semester": "Winter",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "Time-varying operation of chemical and biochemical processes is introduced. Dynamic mathematical models are formulated using material and energy balances. Effects of operational and design parameters on steady-state and dynamic operations are investigated. Numerical techniques are introduced to solve systems of algebraic and differential equations. Numerical and symbolic computation tools are used to analyze dynamic and steady-state process behaviour. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 22,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 20,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 142, CHEE 221, MTHE 225 (MATH 225) or permission of the department ",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "CHEE",
        "code": "223",
        "courseCode": "CHEE 223",
        "id": "CHEE 223 Fluid Mechanics (SAMPLE) 2015-2016",
        "name": "Fluid Mechanics (SAMPLE)",
        "semester": "Winter",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "Principles of momentum and energy transport are applied to the analysis of fluid systems commonly encountered in chemical engineering practice. This approach is via the macroscopic and differential balances of mass, momentum and energy. Topics include fluid statics; incompressible flow in closed conduits; flow and pressure measurement; transportation of fluids; laminar, turbulent and creeping flows; boundary layer effects; sizing of commercial components (piping, tubing, valves, pressure and flow meters and other fittings, as well as pumps) for fluid transport systems in industrial settings. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 42,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "CHEE 221, MTHE 225 ",
        "corequisites": "None ",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "ENCH",
        "code": "211",
        "courseCode": "ENCH 211",
        "id": "ENCH 211 Main Group Chemistry (SAMPLE) 2015-2016",
        "name": "Main Group Chemistry (SAMPLE)",
        "semester": "Fall",
        "hasLecture": 1,
        "hasLab": 1,
        "hasTutorial": 0,
        "description": "An introduction to chemistry of main group inorganic and organic compounds with the use of fundamental quantum mechanics, molecular orbital diagrams and Lewis structures to describe the structure and bonding. The stereochemistry and chirality of organic compounds, solidstate inorganic chemistry, and descriptive chemistry of compounds of the main group elements will be covered. The laboratory will introduce skills in inorganic and organic synthesis. ",
        "professor": "Dr. Tony Noble",
        "notes": "NOTE: Laboratory consumables: estimated cost $20.",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 54,
          "complementaryStudies": 0,
          "engineeringSciences": 0,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 131, APSC 132 ",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "ENCH",
        "code": "212",
        "courseCode": "ENCH 212",
        "id": "ENCH 212 Principles of Chemical Reactivity (SAMPLE) 2015-2016",
        "name": "Principles of Chemical Reactivity (SAMPLE)",
        "semester": "Fall",
        "hasLecture": 1,
        "hasLab": 1,
        "hasTutorial": 0,
        "description": "An introduction to the kinetics and mechanisms of reactions in gaseous and condensed phases, including acid-base and nucleophilic substitution reactions at carbon and other main group centers. Other topics will include molecular dynamics and reactions in solution. The laboratory illustrates measurement techniques and develops laboratory skills. ",
        "professor": "Dr. Tony Noble",
        "notes": "NOTE: Laboratory consumables: estimated cost $20.",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 45,
          "complementaryStudies": 0,
          "engineeringSciences": 0,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 111, APSC 112, APSC 131, APSC 132 ",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "ENCH",
        "code": "245",
        "courseCode": "ENCH 245",
        "id": "ENCH 245 Applied Organic Chemistry I (SAMPLE) 2015-2016",
        "name": "Applied Organic Chemistry I (SAMPLE)",
        "semester": "Winter",
        "hasLecture": 1,
        "hasLab": 1,
        "hasTutorial": 0,
        "description": "A survey of organic functional group reactivity from a mechanistic perspective, including substitution, addition, elimination, rearrangement and redox reactions; extensive use of examples from industrial process chemistry. The laboratory provides experience in organic synthesis, including the preparation, purification and characterization of organic compounds. ",
        "professor": "Dr. Tony Noble",
        "notes": "NOTE: Laboratory consumables: estimated cost $20.",
        "accreditationUnits": {
          "mathematics": 0,
          "naturalSciences": 38,
          "complementaryStudies": 0,
          "engineeringSciences": 16,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "ENCH 211 (CHEM 211), ENCH 212 (CHEM 212) ",
        "corequisites": "",
        "exclusions": "CHEM 223 ",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "ENPH",
        "code": "213",
        "courseCode": "ENPH 213",
        "id": "ENPH 213 Computational Engineering Physics (SAMPLE) 2015-2016",
        "name": "Computational Engineering Physics (SAMPLE)",
        "semester": "Winter",
        "hasLecture": 1,
        "hasLab": 1,
        "hasTutorial": 1,
        "description": "Introduction to the use of numerical methods in solving physics and engineering problems. A high-level language appropriate for engineering, such as MATLAB, will be introduced and used throughout the course. Possible topics to be covered include numerical differentiation and integration, root finding and optimization problems, solution of linear systems of equations, finite-element modelling, fast Fourier transforms and Monte Carlo simulations. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 12,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 21,
          "engineeringDesign": 15,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 142, MTHE 227 (MATH 227), MTHE 237 (MATH 237), ENPH 242 (PHYS 242) ",
        "corequisites": "ENPH 211 (PHYS 211), ENPH 225 (PHYS 225), ENPH 239 ",
        "exclusions": "CMPE 271 ",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      },
      {
        "year": "2015-2016",
        "prefix": "MTHE",
        "code": "225",
        "courseCode": "MTHE 225",
        "id": "MTHE 225 Ordinary Differential Equations (SAMPLE) 2015-2016",
        "name": "Ordinary Differential Equations (SAMPLE)",
        "semester": "F/W/S",
        "hasLecture": 1,
        "hasLab": 0,
        "hasTutorial": 1,
        "description": "First order differential equations, linear differential equations with constant coefficients, and applications, Laplace transforms, systems of linear equations. ",
        "professor": "Dr. Tony Noble",
        "notes": "",
        "accreditationUnits": {
          "mathematics": 42,
          "naturalSciences": 0,
          "complementaryStudies": 0,
          "engineeringSciences": 0,
          "engineeringDesign": 0,
        },
        "labels": {
          "level400": 1,
          "commonCore": 1,
          "eceCore": 0,
          "listB": 0,
          "listC": 1,
          "complementaryCredits": 0,
          "isCustom": 0,
        },
        "prerequisites": "APSC 171, APSC 172, APSC 174  ",
        "corequisites": "",
        "exclusions": "",
        "isCurrentlyOffered": 1,
        "status": "",
        "credits": "3",
        "schedule": [],
      }
    ]
  },
  mutations: {
    updateProgressSidebar(state, value) {
      state.showProgressSidebar = value
    },
    addRecentlyViewed(state, toAdd) {
      var existingIndex = state.recentlyViewedCourses.indexOf(toAdd)
      if (existingIndex != -1) {
        state.recentlyViewedCourses.splice(existingIndex, 1)
      }
      state.recentlyViewedCourses.unshift(toAdd)
    },
  },
  actions: {
  },
  getters: {
    showProgressSidebar: state => state.showProgressSidebar,
    allPrefixes: state => {
      return state.courses.map(course => course.prefix)
    },
    allSearchOptions: state => {
      return state.courses.map(course => course.courseCode + " " + course.name)
    },
    coursesCompleted: state => {
      return state.courses.filter(course => course.status === 'completed')
    },
    coursesInProgress: state => {
      return state.courses.filter(course => course.status === 'inProgress')
    },
    coursesSaved: state => {
      return state.courses.filter(course => course.status === 'saved')
    },
    sumCompletedProperties: (state, getters) => (type, properties) => {
      const courses = getters.coursesCompleted
      var total = 0;
      var i, property;
      if (courses.length >= 1) {
        for (i in properties) {
          property = properties[i];
          if (type === undefined) {
            total += courses
              .map(course => Number(course[property]) || 0)
              .reduce((total, credits) => total + credits);
          } else {
            total += courses
              .map(course => Number(course[type][property]) || 0)
              .reduce((total, credits) => total + credits);
          }
        }
        return total;
      }
      return 0
    },
    sumInProgressProperties: (state, getters) => (type, properties) => {
      const courses = getters.coursesInProgress
      var total = 0;
      var i, property;
      if (courses.length >= 1) {
        for (i in properties) {
          property = properties[i];
          if (type === undefined) {
            total += courses
              .map(course => Number(course[property]) || 0)
              .reduce((total, credits) => total + credits);
          } else {
            total += courses
              .map(course => Number(course[type][property]) || 0)
              .reduce((total, credits) => total + credits);
          }
        }
        return total;
      }
      return 0
    },
    sumSavedProperties: (state, getters) => (type, properties) => {
      const courses = getters.coursesSaved
      var total = 0;
      var i, property;
      if (courses.length >= 1) {
        for (i in properties) {
          property = properties[i];
          if (type === undefined) {
            total += courses
              .map(course => Number(course[property]) || 0)
              .reduce((total, credits) => total + credits);
          } else {
            total += courses
              .map(course => Number(course[type][property]) || 0)
              .reduce((total, credits) => total + credits);
          }
        }
        return total;
      }
      return 0
    },
  },
})
